HouseOfBurt/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using HouseOfBurt.Models;
using HouseOfBurt.Services;
using HouseOfBurt.Utilities;

namespace HouseOfBurt.Controllers
{
    public class ApplicationController : Controller
    {
        #region Class Level Variables

        private ContextIsNeeded_Question[] questions = DataService.Instance.Database.ContextIsNeededQuestions.ToArray();

        List<Tuple<string, int, int>> images = new List<Tuple<string, int, int>>
            {
                new Tuple<string, int, int>("../Content/img/BuisnessSuitWonder.jpg",20,65),
                new Tuple<string, int, int>("../Content/img/ComputerAsk.jpg", 20,65),
                new Tuple<string, int, int>("../Content/img/LaptopWonder.jpg", 20,70),
                new Tuple<string, int, int>("../Content/img/KidWonder.jpg", 20,65),
                new Tuple<string, int, int>("../Content/img/LadyWonder.jpg", 30,55)
            };

        private EmailService emailService;
        private EmailService EmailSvc
        {
            get { return emailService ?? (emailService = new EmailService()); }
        }

        #endregion Class Level Variables

        // GET: Application
        [CompressFilter]
        public ActionResult Index()
        {
            ViewBag.WebApplications = DataService.Instance.Database.WebApplications.ToList();
            return View();
        }

        public ActionResult FresnoPopulationMap()
        {
            return View();
        }

        public ActionResult ContextIsNeeded()
        {
            return View();
        }

        [HttpPost]
        public JsonResult ContextSubmission(object[] link)
        {
            Uri url;
            bool result = Uri.TryCreate(link[0].ToString(), UriKind.Absolute, out url) && url.Scheme == Uri.UriSchemeHttp;

            if (result)
            {
                EmailSvc.SendSelfEmail("ContextIsNeeded Submission", url.ToString());

                return new JsonResult() {Data = "sucess"};
            }

            return new JsonResult() { Data = "failure"};
        }

        public JsonResult ContextNeededEndpoint()
        {
            var json = new JsonResult();
            var random = new Random();
            var image = images[random.Next(images.Count)];
            var question = questions[random.Next(questions.Length)];

            json.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            json.Data = new
            {
                url = image.Item1,
                top = image.Item2,
                left = image.Item3,
                caption = question.Caption,
                link = question.Url
            };

            return json;
        }
    }
}

HouseOfBurt/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HouseOfBurt.Models;
using HouseOfBurt.Utilities;

namespace HouseOfBurt.Controllers
{
    public class NewsController : Controller
    {

        // GET: News
        [CompressFilter(Order = 1)]
        [OutputCache(Duration = 300, Order = 2)]
        public ActionResult Index()
        {
            var articles = DataService.Instance.Database.Articles.OrderByDescending(x => x.CreationDate).Take(10).ToList();
            ViewBag.NewsItems = articles;
            ViewBag.Header = "News Items";
            ViewBag.Links = articles.SelectMany(article => article.Links).ToList();
            return View("Index");
        }

        [CompressFilter]
        public ActionResult Category(string category)
        {
            Category filter = DataService.Instance.Database.Categories.FirstOrDefault(x => x.Caption == category);

            ViewBag.Header = Char.ToUpper(category[0]) + category.Substring(1) + " News:";
            var articles = DataService.Instance.Database.Articles.ToList();
            var newsItems = articles.Where(n => n.Tags.Contains(filter));
            if (!newsItems.Any()) newsItems = DataService.Instance.Database.Articles.ToList();
            ViewBag.NewsItems = newsItems;
            ViewBag.Links = newsItems.SelectMany(a => a.Links).ToList();
            return View("Index");
        }

        [CompressFilter]
        public ActionResult Article(string id)
        {
            var newsArticle = DataService.Instance.Database.Articles.FirstOrDefault(x => x.Slug == id);
            if (newsArticle == null) return RedirectToAction("Index");
            ViewBag.Article = newsArticle;
            return View();
        }
    }
}

HouseOfBurt/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HouseOfBurt.Models;
using HouseOfBurt.Utilities;

namespace HouseOfBurt.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        [CompressFilter(Order = 1)]
        [OutputCache(Duration = 86400, Order = 2)]
        public ActionResult Index()
        {
            var products = DataService.Instance.Database.Products;
            ViewBag.Products = products;
            ViewBag.Links = products.Select(x => x.SourceLink);
            return View();
        }

        [CompressFilter]
        public ActionResult Detail(string id)
        {
            Product product = DataService.Instance.Database.Products.FirstOrDefault(x => x.Slug == id);
            if (product == null) return RedirectToAction("Index");

            ViewBag.Product = product;
            ViewBag.Links = product.SourceLink;
            return View();
        }

        [CompressFilter(Order = 1)]
        [OutputCache(Duration = 86400, Order = 2)]
        public ActionResult License()
        {
            return View();
        }
    }
}

HouseOfBurt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta property="og:title" content="@ViewBag.Title" />
    <link rel="icon" type="image/png" href="/Content/icon/favicon-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/Content/icon/favicon-160x160.png" sizes="160x160">
    <link rel="icon" type="image/png" href="/Content/icon/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/Content/icon/favicon-16x16.png" sizes="16x16">
    <link rel="icon" type="image/png" href="/Content/icon/favicon-32x32.png" sizes="32x32">
    @RenderSection("Meta", required:false)
</head>
    <body>
        <div class="container-fluid">
            <div role="navigation" class="navbar navbar-default navbar-inverse navbar-fixed-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("Home", "Index", "Home", null, new { @class = "navbar-brand" })
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-inverse">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">News <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Software News", "Category", "News", new { @category = "Software" }, new { @role = "menuitem" })</li>
                                    <li>@Html.ActionLink("Blog Posts", "Category", "News", new { @category = "Personal" }, new { @role = "menuitem" })</li>
                                    <li class="divider"></li>
                                    <li>@Html.ActionLink("All News", "Index", "News", null, new { @role = "menuitem" })</li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Service Tag Reporter", "Detail", "Product", new { @id = "Service-Tag-Reporter" }, new { @role = "menuitem" })</li>
                                    <li>@Html.ActionLink("HP Warranty Reporter", "Detail", "Product", new { @id = "HP-Warranty-Reporter" }, new { @role = "menuitem" })</li>
                                    <li>@Html.ActionLink("File Zapper", "Detail", "Product", new { @id = "File-Zapper" }, new { @role = "menuitem" })</li>
                                    <li>@Html.ActionLink("Deal O Round", "Detail", "Product", new { @id = "Deal-O-Round" }, new { @role = "menuitem" })</li>
                                    <li>@Html.ActionLink("All Products", "Index", "Product", null, new { @role = "menuitem" })</li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Source Code<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="https://bitbucket.org/HouseOfBurt/service-tag-reporter/src">Service Tag Reporter Repo<span class="caret"></span></a></li>
                                    <li>@Html.ActionLink("All Products", "Index", "Product")</li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Applications<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Context Is Needed", "ContextIsNeeded", "Application")</li>
                                    <li>@Html.ActionLink("Fresno Population Map", "FresnoPopulationMap", "Application")</li>
                                    <li>@Html.ActionLink("All Applications", "Index", "Application", null, new { @role = "menuitem" })</li>
                                </ul>
                            </li>
                            <li class="navbar-link">@Html.ActionLink("Resume", "Resume", "Home")</li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                @using (Html.BeginForm("Search", "Home"))
                                {
                                    @Html.TextBox("search", null, new { @class = "" })
                                    <a class="glyphicon glyphicon-search padRight20"></a>
                                }
                            </li>
                        </ul>

                    </div>
                </div>
            </div>

            <div class="container-fluid">
                <div class="row-fluid">
                    @if (IsSectionDefined("SideBarContent"))
                    {
                        <div id="sidebar" class="col-lg-3 col-md-2">

                            <div class="list-group">
                                <a href="#" class="list-group-item active">Important Links</a>
                                @RenderSection("SideBarContent", required: false)
                            </div>
                        </div>
                    }
                    <div id="content" class=@(IsSectionDefined("SideBarContent") ? "col-lg-9 col-md-10" : "span12")>
                        @RenderBody()
                        <footer>
                            <p>&copy; @DateTime.Now.Year - House Of Burt Software</p>
                        </footer>
                    </div>
                </div>
            </div>

            @Styles.Render("~/Content/base/css")
            @Scripts.Render("~/bundles/modernizr")
            @RenderSection("css", required: false)

            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
            @Scripts.Render("~/bundles/layoutjs")
        </div>
    </body>
</html>